Add Code of Conduct
containers/docs pull request #1
Opened 2020-02-08 22:22 UTC by TomSweeneyRedHat

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

As the title says.

2020-02-09 02:33 UTC, LorbusChris requested changes

2020-02-09 02:33 UTC, LorbusChris commented on CODE-OF-CONDUCT.md
> +The Fedore Docs Template  project follows the [Containers Community Code of Conduct](https://github.com/containers/common/blob/master/CODE-OF-CONDUCT.md).
Fedora*

2020-02-10 13:46 UTC, TomSweeneyRedHat commented on CODE-OF-CONDUCT.md
> +The Fedore Docs Template  project follows the [Containers Community Code of Conduct](https://github.com/containers/common/blob/master/CODE-OF-CONDUCT.md).
oops, ty, will push a fix shortly.

2020-02-10 14:21 UTC, rhatdan commented
LGTM

2020-02-10 14:21 UTC, merged