Document OSBS add_help prebuild plugin behavior
containers/docs pull request #5
Opened 2020-08-02 10:04 UTC by athos-ribeiro

OSBS can convert a help.md file placed in the dist-git root to a /help.1
man page to be shipped in the built container image. Therefore, there is
no need for copying either a man page or a README.md file into the
image.

Signed-off-by: Athos Ribeiro <athoscr@fedoraproject.org>

Cc @cverna

2020-08-02 12:08 UTC, rhatdan commented
LGTM

2020-08-03 20:30 UTC, LorbusChris requested changes
I found two typos and a missing preposition :)

2020-08-03 20:30 UTC, LorbusChris commented on modules/ROOT/pages/guidelines/help_file.adoc
> +Just like traditional packages, containers need some "man page" information about how they are to be used, configured, and integrated into a larger stack. As such, a Help File is required as part of
`reposotory root prior triggering` -> `repository root prior to triggering`

2020-08-03 20:30 UTC, LorbusChris commented on modules/ROOT/pages/guidelines/help_file.adoc
> +OSBS will automaticlly convert this file into a man page and copy it to `/help.1` in the built image.
`automaticlly` -> `automatically`

2020-10-29 15:57 UTC, rhatdan commented
@athos-ribeiro Still working on this?

2021-02-19 10:00 UTC, athos-ribeiro commented
Sorry for the delay here. Got lost on some notifications after github changed their interface.

I applied the fixes and re-based the branch on master

2021-04-19 13:04 UTC, cverna approved these changes
Thanks

2021-04-19 13:04 UTC, merged